import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">GFS test</a>
        </h1>

        <div className={styles.grid}>
          <Link href="./test1" className={styles.card}>
            <div>Test 1 </div>
          </Link>
          <Link href="./test2" className={styles.card}>
            <div>Test 2 </div>
          </Link>

          <Link href="./test3" className={styles.card}>
            <div>Test 3 </div>
          </Link>

          <Link href="./test4" className={styles.card}>
            <div>Test 4 </div>
          </Link>
        </div>
      </main>
    </div>
  );
}
